title: "Donte Sliger" # your name (or website title) here
logo: "/images/portfolio.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Self taught data analyst who has spent the past year 
  learning all the necessary skills for data analysis 
  through sources such as code academy, youtube, and 
  stratascratch.
  <br><br>
  This portfolio is comprised of mainly independent 
  projects that have caught my attention, along with 
  a few guided projects in the python section.
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
